/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router

declare module "vue-router" {
  interface RouteNamedMap {
    "root": RouteLocationResolvedTyped<{ path: "/"; query?: undefined; hash?: undefined; params: Record<string, never> }>,
    "$error": RouteLocationResolvedTyped<{ path: "/:catchAll(.*)*"; query?: undefined; hash?: undefined; params: { catchAll?: (string | string[])[] } }>,
    "login": RouteLocationResolvedTyped<{ path: "/login"; query?: undefined; hash?: undefined; params: Record<string, never> }>,
    "user-page": RouteLocationResolvedTyped<{ path: "/user-page"; query?: undefined; hash?: undefined; params: Record<string, never> }>,
    "transaction-page": RouteLocationResolvedTyped<{ path: "/transaction-page"; query?: undefined; hash?: undefined; params: Record<string, never> }>,
  }
}

export {}
